
from fonks import (lower,talkUS,myCommand,opn_gl, open_yt, open_dc,open_wp,open_tlg,open_cal,open_gedit,open_clden,open_atom,sy_hlo,sy_fine,sy_ty,
open_tw,wh_made,tk_nte,rd_nte,dl_nte,py_musc,py_stp,th_tme,th_dy,pc_kpt,pc_yndn,
pc_otrm,cl_brwsr,gl_mps,wk_pdia,gl_srch,gl_how,yt_srch,cpu_inf,hdd_inf,     #burda fonksiyonları import ederek tanımlamış oluyoruz..
ram_inf,wh_temp,jr_down,fb_msg,wb_cm,fb_lgn,gthb_lgn,inst_lng,spd_tst,twtt_lgn,fod_rder,gl_trns,mail_snd,change_bckgrnd,cpy_text,paste_text,music_spotify)


#Komutları bir dictionary içine atıyoruz

def command_list(argument):


    switcher = {
    "google aç":opn_gl,
    "google'ı aç":opn_gl,
    "google":opn_gl,
    "aç google":opn_gl,
    "tarayıcıyı aç":opn_gl,
    "tarayıcı mı aç":opn_gl,
    "web tarayıcımı aç":opn_gl,
    "web tarayıcısını aç":opn_gl,
    "google lütfen":opn_gl,
    "google açılsın":opn_gl,
    "google açar mısın":opn_gl,
    "google'ı açsana":opn_gl,
    "google google":opn_gl,


    "youtube":open_yt,
    "youtube youtube":open_yt,
    "you tube":open_yt,
    "youtube'u aç":open_yt,
    "aç youtube":open_yt,
    "youtube'u açar mısın":open_yt,
    "youtube'u açsana":open_yt,


    "discord":open_dc,
    "discord'u aç":open_dc,
    "diskord":open_dc,
    "discort":open_dc,

    "whatsapp":open_wp,
    "watsap":open_wp,
    "whatsapp'ı aç":open_wp,
    "whatsapp'ı açar mısın":open_wp,
    "whatsapp açsana":open_wp,

    "telegram":open_tlg,
    "telegram'ı aç":open_tlg,
    "telegramı aç":open_tlg,
    "teleramı mı aç":open_tlg,

    "hesap makinesi":open_cal,
    "hesap makinesini aç":open_cal,
    "hesap makinemi aç":open_cal,

    "takvim":open_clden,
    "takvimi aç":open_clden,

    "atomu aç":open_atom,
    "atom editörü aç":open_atom,
    "atom":open_atom,

    "not defteri":open_gedit,
    "not defterimi aç":open_gedit,
    "not defterini aç":open_gedit,

    "twitch":open_tw,
    "canlı yayın aç":open_tw,
    "canlı yayın":open_tw,
    "tiviç":open_tw,


    "selam":sy_hlo,
    "selam merhaba":sy_hlo,
    "merhaba":sy_hlo,
    "hey jarvis":sy_hlo,
    "hey dostum":sy_hlo,
    "dostum":sy_hlo,
    "ben geldim":sy_hlo,
    "geldim":sy_hlo,
    "alo":sy_hlo,
    "hey merhaba":sy_hlo,

    "nasılsın":sy_fine,
    "nasıl gidiyor":sy_fine,
    "naber":sy_fine,
    "ne haber":sy_fine,
    "keyifler nasıl":sy_fine,
    "durumun ne":sy_fine,
    "durumlar":sy_fine,
    "durumlar ne":sy_fine,
    "durumlar nasıl":sy_fine,

    "teşekkürler":sy_ty,
    "teşekkür ederim":sy_ty,
    "teşekkür":sy_ty,
    "çok sağ ol":sy_ty,
    "sağ ol":sy_ty,
    "sağol":sy_ty,
    "saol":sy_ty,
    "efsane":sy_ty,
    "harikasın":sy_ty,
    "çok teşekkürler":sy_ty,
    "inanılmazsın":sy_ty,
    "mükemmelsin":sy_ty,

    "kimsin":wh_made,
    "seni kim yarattı":wh_made,
    "seni kim oluşturdu":wh_made,
    "seni kim yazdı":wh_made,
    "seni kim kodladı":wh_made,

    "not al":tk_nte,
    "not tut":tk_nte,
    "not":tk_nte,
    "not alır mısın":tk_nte,
    "söyleyeceklerimi bir yere kaydet":tk_nte,
    "not tutar mısın":tk_nte,

    "notları oku":rd_nte,
    "notumu oku":rd_nte,
    "notu okur musun":rd_nte,
    "notu okusana":rd_nte,
    "notlarımı oku":rd_nte,

    "notumu sil":dl_nte,
    "notları sil":dl_nte,
    "tuttuğun notları sil":dl_nte,

    "müzik çal":py_musc,
    "müzik oynat":py_musc,
    "listemden müzik oynat":py_musc,
    "müzik listemi çal":py_musc,
    "playlist":py_musc,
    "play list":py_musc,
    "müzik listem":py_musc,

    "müzik dur":py_stp,
    "müzik kes":py_stp,
    "müziği durdur":py_stp,
    "müziği dur dur":py_stp,
    "müziği kes":py_stp,
    "müziği kapat":py_stp,
    "playlist'i kapat":py_stp,
    "müzik listemi kapat":py_stp,

    "saat kaç":th_tme,
    "saat":th_tme,
    "saat kaç aceba":th_tme,
    "kaç saat":th_tme,
    "zaman":th_tme,

    "günlerden ne":th_dy,
    "bugün günlerden ne":th_dy,
    "bugün ayın kaçı":th_dy,
    "ayın kaçı":th_dy,
    "günlerden":th_dy,
    "günlerden ne":th_dy,
    "bugün ayın":th_dy,

    "bilgisayarımı kapat":pc_kpt,
    "kapat bilgisayarı":pc_kpt,
    "bilgisayarımı kapatırmısın":pc_kpt,
    "bilgisayarı kapat":pc_kpt,

    "bilgisayarı yeniden başlat":pc_yndn,
    "bilgisayarımı yeniden başlat":pc_yndn,
    "bilgisayara restart atar mısın":pc_yndn,
    "bilgisayara restart at":pc_yndn,

    "oturumumu kapat":pc_otrm,
    "uykuya al":pc_otrm,
    "bilgisayar oturumunu kapat":pc_otrm,
    "uyku moduna al":pc_otrm,
    "bilgisayarımı uyku moduna al":pc_otrm,

    "tarayıcı mı kapat":cl_brwsr,
    "tarayıcımı kapat":cl_brwsr,
    "kapat tarayıcıyı":cl_brwsr,
    "browser'ı kapat":cl_brwsr,
    "web browser'ı kapat":cl_brwsr,
    "interneti kapat":cl_brwsr,
    "tarayıcıyı kapat":cl_brwsr,

    "haritalar":gl_mps,
    "google haritalar":gl_mps,
    "haritaları aç":gl_mps,
    "google maps":gl_mps,
    "google map":gl_mps,
    "maps":gl_mps,
    "neresi":gl_mps,
    "nerede":gl_mps,
    "nerededir":gl_mps,


    "wikipedia":wk_pdia,
    "vikipedia":wk_pdia,
    "vikipedi":wk_pdia,


    "araştır":gl_srch,
    "google ile araştır":gl_srch,
    "google da arama yap":gl_srch,
    "google'da arama yap":gl_srch,
    "google'ı açıp araştır":gl_srch,
    "bunu araştır":gl_srch,
    "araştırmalısın":gl_srch,
    "araştırsana":gl_srch,
    "merak ettim araştırsana":gl_srch,
    "arama yap":gl_srch,
    "google ile ara":gl_srch,
    "google da ara":gl_srch,
    "bunu araştırsana":gl_srch,
    "google ile arama yap":gl_srch,

    "nasıl yapılır":gl_how,
    "nasıl yapılmalı":gl_how,
    "aceba nasıl yapılıyor":gl_how,
    "nasıl yapıldığını ara":gl_how,
    "bu nasıl yapılıyor":gl_how,
    "nasıl yapılıyor":gl_how,
    "google ile öğren":gl_how,
    "bunun nasıl yapıldığını anlat":gl_how,

    "şarkı açsana":yt_srch,
    "şarkı açar mısın":yt_srch,
    "şarkı açmalısın":yt_srch,
    "şarkı çal":yt_srch,
    "video açsana":yt_srch,
    "video açar mısın":yt_srch,
    "youtube da arama yap":yt_srch,
    "youtube ile arama yap":yt_srch,
    "youtube'da ara":yt_srch,
    "komik video aç":yt_srch,
    "trendlerde ne var aceba":yt_srch,
    "trendler ne durumda":yt_srch,
    "bugün hangi video trend":yt_srch,
    "youtube ile arasana":yt_srch,

    "işlemci":cpu_inf,
    "işlemci hakkında bilgi":cpu_inf,
    "işlemci durumu":cpu_inf,
    "işlemci hakkında":cpu_inf,
    "işlemci kullanımı":cpu_inf,

    "hdd kullanımı":hdd_inf,
    "hdd":hdd_inf,
    "hdd durumu":hdd_inf,
    "disk kullanımı":hdd_inf,
    "disk durumu":hdd_inf,
    "hard disk durumu":hdd_inf,
    "hard disk hakkında bilgi":hdd_inf,
    "hardisk":hdd_inf,
    "hard disk":hdd_inf,
    "harddisk":hdd_inf,

    "ram kullanımı":ram_inf,
    "rem kullanımı":ram_inf,
    "rem":ram_inf,
    "ram":ram_inf,
    "bellek kullanımı":ram_inf,
    "bellek":ram_inf,
    "bellek hakkında bilgi":ram_inf,

    "hava durumu":wh_temp,
    "hava":wh_temp,
    "hava nasıl":wh_temp,
    "hava raporu":wh_temp,
    "bugün hava nasıl":wh_temp,
    "bugün kü hava durumu":wh_temp,
    "bugün kü hava durumu":wh_temp,
    "hava kaç derece":wh_temp,
    "hava sıcaklığı":wh_temp,
    "sıcaklık kaç":wh_temp,
    "derece":wh_temp,
    "kaç derece":wh_temp,

    "sistemi kapat":jr_down,
    "uyu kapat":jr_down,
    "uyu":jr_down,
    "kendini kapat":jr_down,
    "uyu uyu":jr_down,
    "kapat kapat":jr_down,
    "kapat uyu":jr_down,
    "kapan":jr_down,
    "kapansana":jr_down,
    "kapanmalısın":jr_down,
    "kendini kapa":jr_down,
    "bugünlük bu kadar":jr_down,
    "kapan artık":jr_down,
    "biraz uyu":jr_down,

    "facebook ile mesaj gönder":fb_msg,
    "facebook mesajı gönder":fb_msg,
    "facebooktan mesaj gönder":fb_msg,
    "mesaj gönder":fb_msg,
    "mesaj gönderecektim":fb_msg,
    "mesaj yazmalıyım":fb_msg,
    "mesaj at":fb_msg,

    "web cam":wb_cm,
    "webcam":wb_cm,
    "webkem":wb_cm,
    "web kem":wb_cm,
    "kamera":wb_cm,
    "kamerayı aç":wb_cm,
    "kameramı aç":wb_cm,
    "kamerayı açsana":wb_cm,
    "kameramı açar mısın":wb_cm,
    "yüzümü tanı":wb_cm,
    "beni tanı":wb_cm,

    "facebook hesabıma gir":fb_lgn,
    "facebook hesabıma giriş yap":fb_lgn,
    "facebook":fb_lgn,
    "facebook giriş yap":fb_lgn,
    "facebook'a giriş yap":fb_lgn,
    "facebook aç":fb_lgn,
    "facebook'u aç":fb_lgn,
    "facebook hesabımı aç":fb_lgn,

    "github":gthb_lgn,
    "git hap":gthb_lgn,
    "git hub":gthb_lgn,
    "git hab":gthb_lgn,
    "git":gthb_lgn,
    "git up":gthb_lgn,
    "gidhub": gthb_lgn,
    "gid hub":gthb_lgn,
    "gid hab":gthb_lgn,
    "gid hub":gthb_lgn,
    "github profilim":gthb_lgn,
    "git hub profilimi aç": gthb_lgn,
    "github profilimi açar mısın":gthb_lgn,

    "hız testi":spd_tst,
    "internet hız testi":spd_tst,
    "internet hızı":spd_tst,
    "internet durumu":spd_tst,
    "internet hakkında":spd_tst,
    "internet hakkında bilgi":spd_tst,
    "internetimin dururmu":spd_tst,
    "internetimin hızı":spd_tst,

    "instagram":inst_lng,
    "ınstagram":inst_lng,
    "instagram hesabım":inst_lng,
    "instagram hesabıma giriş":inst_lng,
    "instagram hesabımı açar mısın":inst_lng,
    "instagram aç":inst_lng,

    "twitter":twtt_lgn,
    "twitt":twtt_lgn,
    "twitt aç":twtt_lgn,
    "twitter hesabım":twtt_lgn,
    "twitter aç":twtt_lgn,
    "twitter hesabıma giriş yap":twtt_lgn,
    "twitter hesabıma gir":twtt_lgn,

    "google çeviri": gl_trns,
    "google çeviriyi aç":gl_trns,
    "google ile çeviri yap":gl_trns,
    "çevir":gl_trns,
    "çeviri":gl_trns,
    "çeviri yap":gl_trns,

    "yemek sepeti siparişi":fod_rder,
    "yemeksepeti":fod_rder,
    "yemek sepeti":fod_rder,
    "pizza siparişi ver":fod_rder,
    "canım pizza çekti":fod_rder,
    "pizza siparişi verir misin":fod_rder,
    "pizza istiyorum":fod_rder,
    "karnım acıktı":fod_rder,
    "acıktım":fod_rder,
    "burger":fod_rder,
    "bur ger":fod_rder,
    "burger sipariş et":fod_rder,



    "gmail":mail_snd,
    "gimail":mail_snd,
    "g mail":mail_snd,
    "gi mail":mail_snd,
    "e-posta gönder":mail_snd,
    "posta gönder":mail_snd,
    "eposta gönder":mail_snd,
    "e-mail gönder":mail_snd,
    "mail gönder":mail_snd,
    "mail":mail_snd,
    "meil":mail_snd,
    "meil gönder":mail_snd,

    

    "arka planı değiştir":change_bckgrnd,
    "arkaplanı değiştir":change_bckgrnd,
    "resimi değiştir":change_bckgrnd,
    "masa üstü arkaplanı değiştir":change_bckgrnd,
    "resmi değiştir":change_bckgrnd,
    "fotoğrafı değiştir":change_bckgrnd,

    "kopyala":cpy_text,
    "metni kopyala":cpy_text,
    "bunu kopyala":cpy_text,
    "söyleyeceğim kelimeyi kopyala":cpy_text,
    "şunu kopyala":cpy_text,
    "kopyala bunu":cpy_text,

    "yapıştır":paste_text,
    "metni yapıştır":paste_text,
    "yapıştırsana":paste_text,
    "bunu yapıştır":paste_text,
    "şunu yapıştır":paste_text,
    "yapıştır onu":paste_text,

    "spotify":music_spotify,
    "sıpotifi":music_spotify,
    "spotify'i aç":music_spotify,
    "sıpotifiyi aç":music_spotify,
    "spotify ile müzik aç":music_spotify,
    


    }

    func = switcher.get(argument, lambda: talkUS("Üzgünüm, komut listemde böyle bir komut yok."));
    func();




while True:
    command = myCommand();
    command = command.lower()
    command_list(command)
